services:
  mysqldb:
    image: mysql:latest
    container_name: AntonDB
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_APPLICATION_USER}
      MYSQL_PASSWORD: ${DB_APPLICATION_PASSWORD}
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./enable_plugins:/etc/rabitmq/enable_plugins:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}